---

- name: create log dir
  file: path=/etc/pm2/ state=directory mode=0755
  become: true

- name: copy conf file
  copy: src={{conf_file}} dest=/etc/pm2/{{name}}.yml
  when: conf_file is defined and name is defined
  become: true

- template: src=conf.yml dest=/etc/pm2/{{name}}.yml
  when: conf_file is not defined and name is defined
  become: true

- name: start pm2
  shell: pm2 startOrRestart /etc/pm2/{{name}}.yml
  become: true
